name       : pandoc-include-code
version    : 1.4.0.0
release    : 1
source     :
    - https://hackage.haskell.org/package/pandoc-include-code-1.4.0.0/pandoc-include-code-1.4.0.0.tar.gz : a9abf64eb4e8b093a1ec16fd93cef16a95015b665759034bded15e47b5576d68
license    : MPL-2.0
component  : office
summary    : A Pandoc filter for including code from source files
description: |
     A Pandoc filter for including code from source files
builddeps  :
    - haskell-cabal-install
    - haskell-pandoc-types-devel
rundeps    :
    - devel:
        - haskell-pandoc-types-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
